CURRENT_WEATHER_TAGS: list[str] = [  'location.localtime',
           'current.last_updated',
           'current.temp_c',
           'current.condition.text',
           'current.wind_kph',
           'current.wind_degree',
           'current.wind_dir',
           'current.pressure_mb',
           'current.precip_mm',
           'current.precip_in',
           'current.humidity',
           'current.cloud',
           # 'current.feelslike_c',
           # 'location.name',
           # 'location.region',
           # 'location.country',
           # 'location.lat',
           # 'location.lon',
           # 'location.tz_id',
           # 'location.localtime_epoch',
           # 'current.last_updated_epoch',
           # 'current.temp_f',
           # 'current.is_day',
           # 'current.condition.icon',
           # 'current.condition.code',
           # 'current.wind_mph',
           # 'current.pressure_in',
           # 'current.feelslike_f',
           # 'current.vis_km',
           # 'current.vis_miles',
           # 'current.uv',
           # 'current.gust_mph',
           # 'current.gust_kph',
           # 'current.air_quality.co',
           # 'current.air_quality.no2',
           # 'current.air_quality.o3',
           # 'current.air_quality.so2',
           # 'current.air_quality.pm2_5',
           # 'current.air_quality.pm10',
           # 'current.air_quality.us-epa-index',
           # 'current.air_quality.gb-defra-index'
]

WEATHER_TAGS: list[str] = ['time_epoch',
             'time',
             'temp_c',
             'wind_kph',
             'wind_degree',
             'wind_dir',
             'pressure_mb',
             'precip_mm',
             'humidity',
             'cloud',
             'feelslike_c',
             'windchill_c',
             'vis_km',
             # 'temp_f',
             # 'is_day',
             # 'condition',
             # 'wind_mph',
             # 'pressure_in',
             # 'precip_in',
             # 'feelslike_f',
             # 'windchill_f',
             # 'heatindex_c',
             # 'heatindex_f',
             # 'dewpoint_c',
             # 'dewpoint_f',
             # 'will_it_rain',
             # 'chance_of_rain',
             # 'will_it_snow',
             # 'chance_of_snow',
             # 'vis_miles',
             # 'gust_mph',
             # 'gust_kph',
             # 'uv'
            ]